projects:
  the-beats-app:
    schemaPath: ./schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        maxDepth: 4
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
